### ISSUE TITLE
Submission Button of Assignment Portal Not working

### ISSUE THREAD

**Issue by Riya222-Herald** [rashmi2200/Homework-Management-#8]
The submission button on the assignment portal appears to be non-functional. When attempting to submit assignments, student are unable to proceed and it says fail to submit assignment

**Comment by shrishatuladhar** [comment]
I've investigated the issue with the submission button on the assignment portal. It appears that there was a technical glitch that prevented students from submitting their assignments successfully. I've fixed the issue, and now the submission button should function properly. Students should be able to submit their assignments without any further issues.
